[colors]

[colors.primary]
background = "#ffffff"  # White background
foreground = "#000000"  # Black text

[colors.normal]
black = "#000000"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#ffffff"

[colors.bright]
black = "#000000"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92d0"
cyan = "#a4ffff"
white = "#ffffff"

[font]
normal.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"
size = 12.0


